### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by mark-hahn** [steelbrain/Atom-Package-Upgrader#1]
Installing Package-Upgrader to C:\Users\Administrator\.atom\packages failed.
    Request for package information failed:     UNABLE_TO_VERIFY_LEAF_SIGNATURE

windows 8.1
atom 0.177.0
apm  0.134.0
npm  2.3.0
node 0.10.35
python 2.7.8
git 1.7.11.msysgit.1
visual studio 2013

see https://discuss.atom.io/t/announce-package-upgrader/14896

**Comment by mark-hahn** [comment]
Also

![default jb khv bnc](https://cloud.githubusercontent.com/assets/811455/6196750/96a0619c-b390-11e4-8a37-0b2be3a62d08.gif)

**Comment by mark-hahn** [comment]
show output: UNABLE_TO_VERIFY_LEAF_SIGNATURE

**Comment by steelbrain** [comment]
`apm unpublish` is failing too, It's super weird.

**Comment by mark-hahn** [comment]
sound like something for atom/apm

**Comment by steelbrain** [comment]
I just re-uploaded it with a version number bump and seems to be working for me now. Can you please confirm?

**Comment by mark-hahn** [comment]
Still getting the same error.  Also I just found that `apm search package-upgrader` gives the error also.

**Comment by steelbrain** [comment]
I am not sure about you, But it works for me
```
C:\Users\Anees Iqbal\.atom\packages\atom-open-last-project>apm search package-up
grader
Search Results For 'package-upgrader' (29)
├── Package-Upgrader Auto-Upgrader for Atom Packages (4 downloads, 0 stars)
├── a-package-loader A short description of your package (36 downloads, 0 stars)

├── package-js-generator Generate Atom.io packages in Javascript. Like `package-
generator:generate-package` command but the packages are generated in JS instead
 of CoffeeScript. (142 downloads, 2 stars)
├── package-sync Synchronizes packages installed between computers (867 download
s, 9 stars)
├── package-cop Find package causing an error by logging errors (50 downloads, 3
 stars)
...........
```

**Comment by mark-hahn** [comment]
hmm.  I might have something old stuck in a cache somewhere.  I'll try
again later.

**Comment by mark-hahn** [comment]
I just tried to publish my package and got the same error.  I'll reboot everything and try again.

**Comment by mark-hahn** [comment]
I found the problem.  I was using a proxy with a self-signed cert and apm refused to use that.

**Comment by steelbrain** [comment]
I'm Glad you were able to find the problem.
